name: CI

on:
  # Run on all pull requests that change code.
  pull_request:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Run every time a code change is pushed.
  push:
    paths-ignore:
      - 'README.md'
      - LICENSE
      - .editorconfig
  # Test if things still work each Tuesday morning at 5:39 UTC.
  # This way we will catch incompatible pandoc changes in a timely
  # manner.
  schedule:
    # At 4:17am each Thursday
    - cron: '17 4 * * 4'

jobs:
  test:
    runs-on: ubuntu-latest
    strategy:
      fail-fast: true
      matrix:
        pandoc:
          - latest
          #- edge
          #- 2.19.2

    container:
      image: pandoc/latex:${{ matrix.pandoc }}

    steps:
      - name: Checkout
        uses: actions/checkout@v4

      - name: Install dependencies
        run: apk add make

      - name: Test
        run: make test SOURCE_DIR=""
